const products = [
  {
    id: 1,
    type: "men",
    brand: "Roadster",
    price: 555,
    category: "Men Slim Fit Casual Shirt",
  },
  {
    id: 2,
    type: "men",
    brand: "Roadster",
    price: 2189,
    category: "Men Slim Fit Casual Shirt",
  },
  {
    id: 3,
    type: "men",
    brand: "Arrow",
    price: 889,
    category: "Men Cotton Fit Casual Shirt",
  },
  {
    id: 4,
    type: "men",
    brand: "ONLY",
    price: 1950,
    category: "Men Cotton Fit Casual Shirt",
  },
  {
    id: 5,
    type: "women",
    brand: "ONLY",
    price: 789,
    category: "Women Casual Shirt",
  },
  {
    id: 6,
    type: "women",
    brand: "Roadster",
    price: 950,
    category: "Women Casual Shirt",
  },
  {
    id: 7,
    type: "women",
    brand: "VeroModa",
    price: 1887,
    category: "Casual Shirt",
  },
  {
    id: 8,
    type: "women",
    brand: "VeroModa",
    price: 1350,
    category: "Casual Shirt",
  },
  {
    id: 9,
    type: "men",
    brand: "Arrow",
    price: 1050,
    category: "Striped Casual Shirt",
  },
  {
    id: 10,
    type: "men",
    brand: "Arrow",
    price: 2240,
    category: "Striped Casual Shirt",
  },
  {
    id: 11,
    type: "women",
    brand: "ONLY",
    price: 2800,
    category: "High Low Casual Shirt",
  },
  {
    id: 12,
    type: "women",
    brand: "Roadster",
    price: 2560,
    category: "High Low Casual Shirt",
  },
];
export { products };
