import { Images } from "./Assets/Images/Image";

const products = [
  {
    id: 1,
    type: "men",
    image: Images.men1,
    brand: "Roadster",
    price: 555,
    category: "Men Slim Fit Casual Shirt",
    sortBy: "recommended",
  },
  {
    id: 2,
    type: "men",
    image: Images.men2,
    brand: "Roadster",
    price: 2189,
    category: "Men Slim Fit Casual Shirt",
    sortBy: "new",
  },
  {
    id: 3,
    type: "men",
    image: Images.men3,
    brand: "Arrow",
    price: 889,
    category: "Men Cotton Fit Casual Shirt",
    sortBy: "recommended",
  },
  {
    id: 4,
    type: "men",
    image: Images.men4,
    brand: "ONLY",
    price: 1950,
    category: "Men Cotton Fit Casual Shirt",
    sortBy: "new",
  },
  {
    id: 5,
    type: "women",
    image: Images.women1,
    brand: "ONLY",
    price: 789,
    category: "Women Casual Shirt",
    sortBy: "recommended",
  },
  {
    id: 6,
    type: "women",
    image: Images.women2,
    brand: "Roadster",
    price: 950,
    category: "Women Casual Shirt",
    sortBy: "new",
  },
  {
    id: 7,
    type: "women",
    image: Images.women3,
    brand: "VeroModa",
    price: 1887,
    category: "Casual Shirt",
    sortBy: "new",
  },
  {
    id: 8,
    type: "women",
    image: Images.women4,
    brand: "VeroModa",
    price: 1350,
    category: "Casual Shirt",
    sortBy: "recommended",
  },
  {
    id: 9,
    type: "men",
    image: Images.men5,
    brand: "Arrow",
    price: 1050,
    category: "Striped Casual Shirt",
    sortBy: "new",
  },
  {
    id: 10,
    type: "men",
    image: Images.men6,
    brand: "Arrow",
    price: 2240,
    category: "Striped Casual Shirt",
    sortBy: "recommended",
  },
  {
    id: 11,
    type: "women",
    image: Images.women5,
    brand: "ONLY",
    price: 2800,
    category: "High Low Casual Shirt",
    sortBy: "new",
  },
  {
    id: 12,
    type: "women",
    image: Images.women6,
    brand: "Roadster",
    price: 2560,
    category: "High Low Casual Shirt",
    sortby: "recommended",
  },
];
export { products };
